### ISSUE TITLE
Can't find dynamic library on Xcode 11.3.1 toolchains

### ISSUE THREAD

**Issue by JunyiXie** [michaeleisel/zld#1]
@rpath/libtbbmalloc.dylib (compatibility version 0.0.0, current version 0.0.0)
@rpath/libtbb.dylib (compatibility version 0.0.0, current version 0.0.0)
What versions of these dynamic libraries?

**Comment by michaeleisel** [comment]
Did you install this with the ‘brew’ command from the read me?

**Comment by JunyiXie** [comment]
thanks
