### ISSUE TITLE
Not working with Xcode 13.3

### ISSUE THREAD

**Issue by narlei** [michaeleisel/zld#105]
The latest zld is not working with the newest Xcode version.

Our team uses zld inside the Buck, and after the Xcode 13.3 we're receiving the error:
```
stderr: ld: framework not found Wrap
```

The linker is working by passing the flag `-F` to the framework folder, the framework exists.

![Screen Shot 2022-03-31 at 12 56 59](https://user-images.githubusercontent.com/8092922/161304918-a2ff6247-1573-4fd7-b2c3-9b67a863d359.png)

**Comment by michaeleisel** [comment]
Do you have a minimum reproducible example you could send?

**Comment by michaeleisel** [comment]
Also, does this error occur with ld64 as well, or just zld?

**Comment by narlei** [comment]
The ld64 is working as well, the problem is only with zld. I'll create an example.
