### ISSUE TITLE
DOCS: Note that the full Xcode installation is required, xcode CLI is not enough

### ISSUE THREAD

**Issue by corneliusroemer** [michaeleisel/zld#106]
It would be good if the docs went into a bit more detail about whether the full xcode installation are required for the binary or whether the CLI is enough.

After quite some googling, I realized I needed the actual full 12 GB Xcode installation - the cli tools are not enough to build from source.

I first tried installing via homebrew but I got the same error. It would be good if the requirements were a bit more explicit for people who've never done work with xcode.

The error is (for those googling it)
```
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```

When installing xcode, I first made the mistake of trying to install via the App store. Bad idea, that takes hours to download.

Much better, download the binary from the Apple server linked to here: https://xcodereleases.com/

**Comment by michaeleisel** [comment]
This is already mentioned under "Pre-built binary" and also under "Building from source"

**Comment by corneliusroemer** [comment]
I didn't even know there was a difference between command line tools and full xcode until it dawned on me reading around.

Maybe it could be made explicit that command line tools is not enough.

Or this issue is enough in the future.

**Comment by michaeleisel** [comment]
updated in 509aed7d6eb6b82525e0b963716a279abe16be81
