### ISSUE TITLE
Xcode required vs command line tools?

### ISSUE THREAD

**Issue by fdncred** [michaeleisel/zld#109]
I really don't want to have to install Xcode just to be able to use zld. It's a behemoth that I'd rather avoid. Is there a way to build this with only the command line tools?

**Comment by bjorn3** [comment]
As far as I know that is not possible. Zld is a fork of the official apple linker which uses xcodebuild as build system. Xcodebuild seems to only be shipped with the full Xcode installation.

**Comment by fdncred** [comment]
If that's the case, then it answers my question. I just didn't want to install ~13GB of stuff that I hope to never use since I mainly code in rust. It's a bummer that the installer didn't work on my M1Max, it would've been fun to try it out.
