### ISSUE TITLE
Xcode 14 beta.  Can not Not link _objc_msgSend

### ISSUE THREAD

**Issue by william52328** [michaeleisel/zld#113]
I compiled my project with Xcode14 beta and found that the.a static library could not link to its own library symbols。

Example Like This：
Undefined symbols for architecture arm64:
  "_objc_msgSend$setOffsetFromCenter:", referenced from:
      +[SVProgressHUD setOffsetFromCenter:] in libSVProgressHUD.a(SVProgressHUD.o)
      +[SVProgressHUD resetOffsetFromCenter] in libSVProgressHUD.a(SVProgressHUD.o)
  "_objc_msgSend$unreachableBlock", referenced from:
      -[Reachability reachabilityChanged:] in libReachability.a(Reachability.o)

SetOffsetFromCenter is a symbol in the SVProgressHUD library, but cannot be linked using ZLD。

**Comment by keith** [comment]
You can pass `-fno-objc-msgsend-selector-stubs` to your compiles to avoid this

**Comment by keith** [comment]
You have to do that to clang for each object compile, not ld unfortunately

**Comment by michaeleisel** [comment]
Do you know if lld has a plan for fixing this?

**Comment by keith** [comment]
I started looking at it this morning, not sure how far i'll get

**Comment by aleksandergrzyb** [comment]
👋, is there any progress regarding this issue? 👀

**Comment by keith** [comment]
Sorry to be clear I started working on this for LLD, tracked here https://github.com/llvm/llvm-project/issues/56034, for zld to get this it would either require @michaeleisel to implement it entirely, or apple to update their open source dump of ld64 and zld rebase on it. I would suggest disabling it with `-fno-objc-msgsend-selector-stubs` in the meantime

**Comment by michaeleisel** [comment]
i may just turn that flag on by default

**Comment by michaeleisel** [comment]
oh wait, right, it's a clang flag, not an ld one

**Comment by PhilCai1993** [comment]
I noticed that even if you put `-fno-objc-msgsend-selector-stubs` for all clang invocations, if `-miphoneos-version-min=8.0` is presented in the linker phase, the `_objc_msgSend` issue will happen too.

**Comment by michaeleisel** [comment]
so, my plan is that i will not be fixing this bug. instead, i will detect when it occurs, and in the error message tell the user either to add the `-fno-objc-msgsend-selector-stubs` flag to their compilations, or else switch to lld. i am working with the lld people to make user-friendly lld install docs to send people to

**Comment by michaeleisel** [comment]
1.3.6 has a better error message for this, including a link to the new mach-o lld docs
