### ISSUE TITLE
Add a CI job

### ISSUE THREAD

**Issue by rmaz** [michaeleisel/zld#12]
Once #9 is resolved it would be great to set up a CI job to verify changes.

**Comment by michaeleisel** [comment]
fyi the tests are currently described in https://github.com/michaeleisel/zld/issues/13

i'm ok with a CI job if it has a low maintenance burden. other options would be a script that contributors can run?

**Comment by rmaz** [comment]
Initially could be as simple as a travis config that calls `make`, I think that would at least give some level of confidence for contributed changes. It could be expanded to handle tests once a reproducible test suite was in place. I can put up a PR with an example config.

**Comment by michaeleisel** [comment]
Fair enough, yeah starting with `make` sounds good. A PR would be great.

**Comment by rmaz** [comment]
Added a basic config in #14

**Comment by rmaz** [comment]
Went with a Github action instead, less effort to integrate.
