### ISSUE TITLE
Comparison with mold/sold

### ISSUE THREAD

**Issue by satvikpendem** [michaeleisel/zld#124]
Hi, I've been using [mold](https://github.com/rui314/mold) but they recently changed their license where macOS linking was now a paid feature, however the source is still available. Would you be able to do a comparison/benchmarks on macOS between mold/sold and zld?

**Comment by michaeleisel** [comment]
zld is now in maintenance mode, with lld as the recommended alternative, details here: https://eisel.me/lld . so, i think the interesting comparison would be between lld and sold, not zld and sold
