### ISSUE TITLE
Xcode14.2  MacOS Ventura 13.1 have BUG

### ISSUE THREAD

**Issue by 1987zcc** [michaeleisel/zld#125]
Undefined symbol: _objc_msgSend$initWithName:sessionRole: - this is a zld/Xcode 14 issue, see the bottom of the full error message for details

**Comment by 1987zcc** [comment]
Undefined symbol: _objc_msgSend$role - this is a zld/Xcode 14 issue, see the bottom of the full error message for details

**Comment by michaeleisel** [comment]
See the bottom of the full error message for details
