### ISSUE TITLE
Unable to install through Homebrew

### ISSUE THREAD

**Issue by ajay-mk** [michaeleisel/zld#127]
Tried installing through homebrew with `brew install zld`
```
Warning: No available formula with the name "zld". Did you mean zlog?
==> Searching for similarly named formulae and casks...
==> Formulae
zlog

To install zlog, run:
  brew install zlog

==> Casks
xld

To install xld, run:
  brew install --cask xld
```
I am on M2 MacBook Pro with MacOS Ventura 13.1

**Comment by michaeleisel** [comment]
You can download the latest (and last?) zld release at https://github.com/michaeleisel/zld/releases/tag/1.3.9.1 . But zld is now being archived, so consider lld instead: https://eisel.me/lld
