### ISSUE TITLE
Thorough testing

### ISSUE THREAD

**Issue by michaeleisel** [michaeleisel/zld#13]
this is just a ticket to brainstorm testing

fyi the tests are currently:
- link the "signal", "storage", and "XUL" files used in the benchmarks, then ensure they're byte-for-byte the same as ones linked from a previous version
- run the tests in unit-tests, and see that aren't any more failures than with the open-source original). either i'm doing something wrong in setting them up, or they aren't maintained? they seem valuable but need care and feeding
- run the mozilla app, having linked all its libraries with zld, and see that it looks halfway decent

machochecker, a target in the .xcodeproj, seems helpful for doing some checks. it would be very cool if there's some way to test binary "equivalency", i.e. compensating for differences in ordering etc. and compare it against newest (and thus still closed-source) ld64.

an easy thing to do is just test linking more and more open-source libraries for that byte-for-byte compatibility. certainly there are lots of big ones out there, like llvm

**Comment by rmaz** [comment]
I think passing the bundled unit tests as well as doing a couple of performance comparisons would be a great start. 

> link the "signal", "storage", and "XUL" files used in the benchmarks, then ensure they're byte-for-byte the same as ones linked from a previous version

Worth comparing to the comparable system linker for byte compatibility? Or would the layout differ somehow?

**Comment by michaeleisel** [comment]
Yeah, perf comparisons also. The system linker differs due to optimizations around hashing and unstable sorting, but those optimizations can be disabled by using -DREPRO, in which case it should (last I checked) build same as the linker.

**Comment by michaeleisel** [comment]
I'm noticing non-determinism even when using the same linker. Getting rid of that non-determinism may be a larger project for later, so for now I think we can leave binary reproducibility alone (or at least only test a subset of the binary for equality). As for how to reintegrate the unit tests in a way that's easy for people to use, I think I'll look into putting an XCTest wrapper around all of the tests that actually work, and finding a way to ignore any auto-generated files. Then we can start adding other tests as part of the same XCTest target, e.g. for the 3 linking invocations that I've focused on. The tests will all be put back in and ready by end of next week, no need to worry :) I'm also happy to help if you want to get this done sooner and do the work yourself.

**Comment by michaeleisel** [comment]
Also, there are a lot of interactions with the filesystem in these tests, hopefully that's not a problem for any CI processes

**Comment by michaeleisel** [comment]
Closing for now
