### ISSUE TITLE
zld is missing the force_load fix in Xcode 11

### ISSUE THREAD

**Issue by rmaz** [michaeleisel/zld#16]
Xcode 10.2 introduced a linker bug that caused linking Swift in static libraries to fail:

https://developer.apple.com/documentation/xcode_release_notes/xcode_10_2_release_notes/swift_5_release_notes_for_xcode_10_2?language=objc

> Linking against a static Swift library might create a binary with missing type metadata because the object files that define the metadata inside the static archive are mistakenly considered unused. (47598583)
> 
> This can manifest as a Swift runtime error with a message such as: “failed to demangle superclass of MyClass from mangled name ‘<mangled name>’”.
> 
> Workaround: If you can rebuild the static library, try building it with whole module optimization enabled. Otherwise, add -all_load to the linker flags in the client binary to ensure all object files are linked into it.

This was fixed in Xcode 11:
https://developer.apple.com/documentation/xcode_release_notes/xcode_11_release_notes?language=objc

> Static libraries are now always force-loaded in their entirety during linking, fixing most “unable to demangle” runtime errors. (47598583)

We will need to reimplement this fix. My suspicion is the solution was not as simple as described, that they in fact only added force_load for static libraries that contained Swift symbols. A quote from the [Swift bug ticket](https://bugs.swift.org/browse/SR-10721) has:

> You should be safe if you force load any .a file that contains symbols matching the regex ^_?\$s.*Mn$ (that is, beginning with the prefix $s or _$s, and ending with the suffix Mn)

**Comment by michaeleisel** [comment]
Interesting! Yeah this can be fixed

**Comment by michaeleisel** [comment]
@rmaz you think that the explanation in the Xcode 11 release notes was incorrect? Because I'd like to just copy whatever they did for parity, so even if force loading everything is unnecessary, I'd rather be just as unnecessary as Xcode 11's `ld` is

**Comment by rmaz** [comment]
Simplest IMO would be extending the `-ObjC` code to also check for Swift symbols. The other option would be to first do a pass over the entire archive looking for a Swift symbol to mark the archive as force loadable, but it seemed a little wasteful to do multiple passes for every archive. Thoughts?

**Comment by michaeleisel** [comment]
Yeah multiple passes seems reasonable. What confuses me is that it says, "Static libraries are now always force-loaded in their entirety during linking". However, when I build a mixed ObjC/Swift static lib, and one of the files is an ObjC category (so it would cause issues unless it's been force loaded), it fails to include it. So it seems like, despite what the release notes say, it probably only forcibly includes at the object file level and not at the static library level. But I've asked for clarification in that swift.org ticket

**Comment by michaeleisel** [comment]
s/multiple passes/avoiding multiple passes/

**Comment by rmaz** [comment]
> So it seems like, despite what the release notes say, it probably only forcibly includes at the object file level and not at the static library level.

That was my suspicion too, but I have not closely verified. I know it is not doing `force_load` on all static libraries as our application would be unlinkable in that case. I can confirm that extending the ObjC code path to include Swift symbols works for our code. If you're fine with this approach I can put up a PR tomorrow.

**Comment by michaeleisel** [comment]
Sure, that'd be great! I can run unit tests on my end, and maybe some perf ones too
