### ISSUE TITLE
Document base ld64 version

### ISSUE THREAD

**Issue by kastiglione** [michaeleisel/zld#2]
First of all, this project looks awesome (although, I haven't tried it yet)!

The readme says "open-source one is a bit old (Xcode 10.2)", but doesn't say what zld uses as its base version of ld64. In the source I see a couple mentions of ld64-409.12, but the most recent release of ld64 is 450.3.

**Comment by michaeleisel** [comment]
Originally it was forked from 409, but then I merged in 450, so it's effectively 450. I'll update the readme, thanks for the suggestion!
