### ISSUE TITLE
zld does not support ARM64_32 architecture

### ISSUE THREAD

**Issue by milend** [michaeleisel/zld#37]
The open source dumps of ld64 do not include support for ARM64_32 used by WatchOS. The following file would fail to link with zld.

`hello.c`
```
// xcrun clang -c hello.c -o hello.o -target arm64_32-apple-watchos4.0 -isysroot /var/db/xcode_select_link/Platforms/WatchOS.platform/Developer/SDKs/WatchOS.sdk
// xcrun ld -dylib -arch arm64_32 -watchos_version_min 4.0.0 -syslibroot /var/db/xcode_select_link/Platforms/WatchOS.platform/Developer/SDKs/WatchOS.sdk -o libHello.dylib hello.o -lc

#include <stdio.h>

void hello(void) {
  printf("hello world");
}
```

**Comment by milend** [comment]
@michaeleisel: one potential solution would be to detect `arm64_32` in the arguments list and just exec ld64.

**Comment by michaeleisel** [comment]
FYI, `rg -i arm64_32` returns several results in current master. Are you sure it's not supported?

**Comment by milend** [comment]
@michaeleisel: Yup, it cannot link WatchOS binaries for ARM64_32. If you try the sample above, you will get:

> ld: unknown/unsupported architecture name for: -arch arm64_32

Calling out to ld64 succeeds as expected.

**Comment by milend** [comment]
@michaeleisel As I was doing some investigations, it turns out that zld/open source ld64 cannot link the following architectures which the official ld64 binary can: 

- arm64e
- arm64_32
- armv6m
- armv7em

Running the linkers with `-v`, produces the following outputs:
- `zld: configured to support archs: i386 x86_64 x86_64h armv6 armv7 armv7s armv7m armv7k arm64`
- `ld64: configured to support archs: armv6 armv7 armv7s arm64 arm64e arm64_32 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em`

**Comment by michaeleisel** [comment]
Looking at (the source)[https://github.com/michaeleisel/zld/blob/cbbd9ce7a7515a6e3c879ebb03b5d7b9f4a9172e/ld/src/abstraction/MachOFileAbstraction.hpp#L538], it appears that we just need to toggle on flags like SUPPORT_ARCH_armv7em, which I hadn't thought about before hearing about this arm64_32 issue

**Comment by michaeleisel** [comment]
Interesting... looks like it doesn't compile and it's missing stuff for `Parser<arm64_32>::...`. At least, we can maybe support the other archs. Also, check out this [comment](https://github.com/michaeleisel/zld/blob/master/ld/src/ld/Options.cpp#L736) and let me know if armv7k as a fallback arch would fix this for you.

**Comment by michaeleisel** [comment]
mitigated with https://github.com/michaeleisel/zld/pull/55
