### ISSUE TITLE
Large Binary Instruments Profile Data

### ISSUE THREAD

**Issue by milend** [michaeleisel/zld#38]
I've recorded profiling data ([zld.trace.zip](https://github.com/michaeleisel/zld/files/4489743/zld.trace.zip)) for a large binary which takes several minutes to link. In terms of numbers:

- ld64
  - 225.64s user 17.44s system 94% cpu 4:17.81 total
  - 219.63s user 17.33s system 93% cpu 4:14.00 total
  - 221.44s user 21.93s system 88% cpu 4:35.26 total
- zld
  - 213.75s user 14.14s system 118% cpu 3:12.50 total
  - 218.63s user 16.22s system 115% cpu 3:22.62 total
  - 213.71s user 14.74s system 118% cpu 3:11.99 total

zld is around 1min faster (~23% faster). Machine was rebooted before taking the measurements and the samples taken with hot file caches (i.e., linkers ran before recording the samples above). Machine is a 15" MacBook Pro 2017, i7 3.1GHz, 16GB RAM and 1TB SSD.

**Comment by michaeleisel** [comment]
Thank you!

**Comment by milend** [comment]
@michaeleisel: here's another trace of linking the same exact binary without passing an order file. This cuts the linking time from around 3m15s to 56s. There's still a large section which is single-threaded, so I'm wondering if it can be parallelised – it would result in a huge perf win.

[zld-no-order.trace.zip](https://github.com/michaeleisel/zld/files/4492573/zld-no-order.trace.zip)

**Comment by tcpthecode** [comment]
@milend how did you pass order file into linker ?

**Comment by milend** [comment]
@tcpthecode We use the `-order_file` parameter.

**Comment by tcpthecode** [comment]
Thanks @michaeleisel 👍
