### ISSUE TITLE
Integrate ld-530

### ISSUE THREAD

**Issue by michaeleisel** [michaeleisel/zld#40]
Apple has released ld-520 and ld-530 (thanks to @rmaz for pointing this out), so we can integrate those changes

**Comment by keith** [comment]
Here's the non zld diff https://gist.github.com/keith/df63e16617bf63b74411cc871e6903a5

**Comment by michaeleisel** [comment]
sadly no watch support, but at least it's a simple-looking diff

**Comment by michaeleisel** [comment]
done in https://github.com/michaeleisel/zld/pull/44
