### ISSUE TITLE
error in running Unit Tests with zld linker

### ISSUE THREAD

**Issue by hassan-shahbazi** [michaeleisel/zld#42]
### Description
When I set `-fuse-ld=<zld path>` as the linker flag for xcode, the project stops running unit tests.
I use the following command to run tests over my project
```bash
xcodebuild test -workspace NinchatSDKSwift.xcworkspace -scheme NinchatSDKSwiftTests "OTHER_LDFLAGS=\$(OTHER_LDFLAGS) -fuse-ld=$(which zld)" -destination "platform=iOS Simulator,name=iPhone 8"
```
But I get the following error:
```bash
Testing failed:
        NinchatSDKSwiftTests:
                xctest (82532) encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted. (Underlying error: Crash: xctest (82532): Namespace SIGNAL, Code 0x5))

** TEST FAILED **
```

### Full Log
This [Github Action](https://github.com/somia/ninchat-sdk-ios-swift/actions/runs/124873532) shows a complete log for the steps resulted in the mentioned issue.

### zld Version
This is the output of `zld -v`
```bash
@(#)PROGRAM:zld  PROJECT:zld-
BUILD 11:18:20 Mar 20 2020
configured to support archs: i386 x86_64 x86_64h armv6 armv7 armv7s armv7m armv7k arm64
LTO support using: LLVM version 11.0.3, (clang-1103.0.32.62) (static support for 22, runtime is 26)
TAPI support using: Apple TAPI version 11.0.0 (tapi-1100.0.11)

```

**Comment by michaeleisel** [comment]
hi, do you have some steps for me to reproduce?

**Comment by michaeleisel** [comment]
can i just do a pod install with NinchatSDK?

**Comment by Hassaniiii** [comment]
To reproduce, just clone the [repository](https://github.com/somia/ninchat-sdk-ios-swift), apply required changes to use `zld`, run `pod install`, and then run:
`xcodebuild test -workspace NinchatSDKSwift.xcworkspace -scheme NinchatSDKSwiftTests "OTHER_LDFLAGS=\$(OTHER_LDFLAGS) -fuse-ld=$(which zld)" -destination "platform=iOS Simulator,name=iPhone 8"`
