### ISSUE TITLE
Mac Catalyst linker issues

### ISSUE THREAD

**Issue by steipete** [michaeleisel/zld#43]
zld works great for us overall. We cannot yet enable it for Mac Catalyst. It seems the linker pulls off some tricks to differentiate between AppKit and iOS-versions of the frameworks.

We see the following error:

```
Building for Mac Catalyst, but linking in .tbd built for , file '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks//CoreImage.framework/CoreImage.tbd' for architecture x86_64
```

This might be fixed once https://github.com/michaeleisel/zld/issues/40 is resolved.

Thank you for zld! [Gave the project a shoutout on my blog.](https://steipete.com/posts/zld-a-faster-linker/)

**Comment by michaeleisel** [comment]
new upgrade is in master, https://github.com/michaeleisel/zld/pull/44 , there will also be a release soon i think

**Comment by michaeleisel** [comment]
the new version doesn't fix it. it looks like possibly a tapi issue, will investigate further

**Comment by michaeleisel** [comment]
possible fix, albeit with lots of linker warnings, here: https://github.com/michaeleisel/zld/pull/50

**Comment by steipete** [comment]
Thanks for your work on this! I'll give this a go this week.

**Comment by steipete** [comment]
I've just did a quick test with zld 1.1 from brew + Xcode 12b3, same error.

**Comment by michaeleisel** [comment]
Are you using the new linker flag as per https://github.com/michaeleisel/zld/pull/55#issuecomment-655798318

**Comment by michaeleisel** [comment]
Closing, feel free to reopen if you can confirm that you're using the new flag (also mentioned in the release notes). I'll update the readme as well.

**Comment by michaeleisel** [comment]
Fixed properly in https://github.com/michaeleisel/zld/pull/59
