### ISSUE TITLE
No performance improvement

### ISSUE THREAD

**Issue by MarcoCadei** [michaeleisel/zld#49]
Hi all! :)
I was trying to use this, but I didn't see any improvement in build time. Neither with a clean build nor an incremental one.

Do you have any clue why?
Usual build time is ~70s while incremental build time is ~8s.

**Comment by michaeleisel** [comment]
The improvement mentioned is specifically for the linking time, which is just one component of either of those cases

**Comment by michaeleisel** [comment]
the readme has been updated to better reflect this at 8b8cee4743adcfeb6627ddefe0b519dbf1b12662
