### ISSUE TITLE
duplicate symbol

### ISSUE THREAD

**Issue by Ekulelu** [michaeleisel/zld#57]
there is "duplicate symbol" error when use zld,  these symbols are in different lib.  However, there is only warning when use the origin linker.

**Comment by Ekulelu** [comment]
I found this error is something about "Dead Code Stripping"

**Comment by Ekulelu** [comment]
I turn on the "Dead Code Stripping", but there is also a error, 
ld: Linking globals named '_ZTVN4xxx10network_cl9TcpSocketE': symbol multiply defined! for architecture arm64

**Comment by michaeleisel** [comment]
thanks for the report, do you have a test case i can reproduce? i.e., all the input files such as .o files as well as the invocation

**Comment by michaeleisel** [comment]
also, where did you see that this error was about dead code stripping?

**Comment by Ekulelu** [comment]
"ld: Linking globals named '_ZTVN4xxx10network_cl9TcpSocketE': symbol multiply defined! for architecture arm64"  this error is nothing about dead code stripping. If turn on dead code stripping, there are more duplicate symbols errors. 
Sorry, the project occured the error is owned by company, and I can't give it to you. I will try to create a demo project for you when I have time.

**Comment by michaeleisel** [comment]
sounds good

**Comment by Ekulelu** [comment]
I have tried to create a demo project to reproduce the case, but failed. The demo project works so well.

**Comment by michaeleisel** [comment]
if you delete the cache at `/tmp/zld-*`, and then run zld again, do you still see the same problem?

**Comment by Ekulelu** [comment]
After I deleted the /tmp/zld-* ,  the first time build is ok, but the second time will failed

**Comment by michaeleisel** [comment]
ok, i think i may know the issue. when i get a chance i can dig deeper

**Comment by michaeleisel** [comment]
Can you try the latest release, 1.2.1?

**Comment by Ekulelu** [comment]
Thank you, I will try it on Monday.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2020年10月17日(星期六) 晚上10:41
收件人: "michaeleisel/zld"<zld@noreply.github.com&gt;; 
抄送: "政"<709314090@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [michaeleisel/zld] duplicate symbol (#57)





 
Can you try the latest release, 1.2.1?

**Comment by Ekulelu** [comment]
I try 1.2.1, but it's still failed. The error is also " Linking globals named '_ZTVN4bigo10network_cl9TcpSocketE': symbol multiply defined! for architecture arm64"

**Comment by Ekulelu** [comment]
I find there are some 'TcpSocket.o' in different libraries in the `/tmp/zld-*` file like blow. If I delete all the 'TcpSocket.o', then the link process will report another multiply symbol error. I think the error has something to do with the content of `/tmp/zld-*`, but I don't know how the file effects the link process.

```
xxx/Pods/nerv/nerv.framework/nerv
   ....
   TcpSocket.o
   .....

xxx/Pods/chunklink/chunklink.framework/chunklink
     ....
   TcpSocket.o
   .....

```

**Comment by michaeleisel** [comment]
/tmp/zld-* causes eager loading of all the object files within it. that list consists of all the object files that were loaded for the last linker execution, and it may include object files that would no longer be loaded by stock ld, which in many cases loads lazily

**Comment by ebdjinming** [comment]
I have same problem, is there any advise to solve this problem?

**Comment by michaeleisel** [comment]
Can you provide a reproducible example?

**Comment by ebdjinming** [comment]
Maybe I can have a try.
