### ISSUE TITLE
Xcode 12 support

### ISSUE THREAD

**Issue by michaeleisel** [michaeleisel/zld#58]
according to someone at apple, there's no clear timeline on when the source code for tapi, ld, etc. will ship. i'll wait until end of september for it to happen, and if it hasn't happened, i'll begin reverse-engineering the tapi changes and try to get a stable version for xcode 12 that doesn't have the spurious warnings. @rmaz @keith @milend

**Comment by michaeleisel** [comment]
Done in https://github.com/michaeleisel/zld/pull/59

**Comment by keith** [comment]
awesome! are you planning on shipping a new release with this?

**Comment by michaeleisel** [comment]
yes, although at the moment there's another issue

**Comment by michaeleisel** [comment]
https://github.com/michaeleisel/zld/issues/61 has surfaced

**Comment by michaeleisel** [comment]
#61 has been fixed, along with a newly found issue https://github.com/michaeleisel/zld/pull/66 . it now works for spotify's main app with no warnings
