### ISSUE TITLE
Xcode 12.2 Beta 3: ld: unknown option: -no_adhoc_codesign

### ISSUE THREAD

**Issue by jasonboggess** [michaeleisel/zld#67]
Xcode 12.2 Beta 3 produces the following linker error:

    ld: unknown option: -no_adhoc_codesign

It looks like `-Xlinker -no_adhoc_codesign` is being added to the linker flags.

Removing zld fixed the issue.

**Comment by michaeleisel** [comment]
can you try with latest master, 09ea158feae41f1965784d3cc26e571f7a3f6c84 ? i've added a fix there

**Comment by jasonboggess** [comment]
Awesome. That seems to work.
