### ISSUE TITLE
Missing zld.zip file for 1.2.1 release

### ISSUE THREAD

**Issue by kurrak** [michaeleisel/zld#72]
Hi @michaeleisel,

I just wanted to create pull request in your https://github.com/michaeleisel/homebrew-zld/ to update brew formula to match most recent 1.2.1 release with fix for Xcode 12.2, but I realised I can't do this since there is not zld.zip asset added for 1.2.1 release. 

I wonder if it's something that you don't intent to provide anymore for future releases and I should work on creating formula that builds zld from source. This is first time I do anything with brew formulas so I just wanted to ask before moving on.

Thanks much,
Maciek

**Comment by michaeleisel** [comment]
Thanks for looking into this. Going forwards, it’s just built from source, so you could do that in the formula

**Comment by trzeciak** [comment]
Hi guys,
I updated the tap repo, this is my first encounter with the brew (previously I was just a happy user).

It is a pull requests: https://github.com/michaeleisel/homebrew-zld/pull/1
