### ISSUE TITLE
Installation Docs improvements

### ISSUE THREAD

**Issue by Matthew-Benson** [michaeleisel/zld#77]
If the build process requires cmake to be installed then the installation docs in the readme should list installing cmake and adding it to your PATH as one of the steps.

Also including an example for the default xcode path might be helpful to newer MacOS developers like myself:
`sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`

**Comment by michaeleisel** [comment]
Closed via https://github.com/michaeleisel/zld/issues/78 which offers instructions for downloading it pre-built
