### ISSUE TITLE
ld: unknown option: -platform_version

### ISSUE THREAD

**Issue by iKleMiX** [michaeleisel/zld#8]
Getting this error using Xcode 11.4 Beta 2, when trying to link iOS targets. 
And there isn't even such flag passed in the build log.

**Comment by michaeleisel** [comment]
Yeah, this appears to be a flag that was added in a newer, not-yet-open-sourced ld. Just curious, does it work for you with Xcode 11.3? And can you add "-###" to the linker invocation, which prints the subprocesses it spawns, and paste the output.

**Comment by iKleMiX** [comment]
```
Apple clang version 11.0.3 (clang-1103.0.32.26)
Target: x86_64-apple-macos10.11
Thread model: posix
InstalledDir: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/usr/local/bin/zld" "-demangle" "-lto_library" "/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib" "-dynamic" "-arch" "x86_64" "-exported_symbols_list" "/dev/null" "-force_load" "/Users/klemix/Library/Developer/Xcode/DerivedData/Platform-ganbmvkpevluiwgmzgnsmuyhoaga/Build/Products/Debug/libPlatform-macOS.a" "-force_load" "/Users/klemix/Library/Developer/Xcode/DerivedData/Platform-ganbmvkpevluiwgmzgnsmuyhoaga/Build/Products/Debug/libExternal-macOS.a" "-platform_version" "macos" "10.11.0" "10.15.4" "-syslibroot" "/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk" "-ObjC" "-o" ... other flags releated to an app
```
this is the output with `-###` you can even see `-platform_version` here.
And with `-###` it does link, so I'm not sure it uses zld, once I remove it, it fails again.

I will try to find some time to try to recompile with Xcode 11.3 later.

**Comment by michaeleisel** [comment]
The `-###` appears to fix it simply because that option prevents actual linking from occurring, it's more like a dry-run

**Comment by iKleMiX** [comment]
Tested in Xcode 11.3 and it does work. So the problem is only with the new Xcode 11.4.

**Comment by michaeleisel** [comment]
Fixed in https://github.com/michaeleisel/zld/pull/23

**Comment by rmaz** [comment]
Looks like its just a generic way of passing in the deployment target instead of using `-ios_version_min` and friends.

https://reviews.llvm.org/D71579

Should be easy enough to convert on the way in to match the old behaviour (assuming the format of `LC_BUILD_VERSION` remains the same).

**Comment by michaeleisel** [comment]
Yep, good call. Hopefully that llvm.org will have some insights on our other outstanding questions as well
