### ISSUE TITLE
Recommending the -x flag

### ISSUE THREAD

**Issue by michaeleisel** [michaeleisel/zld#88]
@bogardon informed me that the `-x` flag was speeding up linking for him. Indeed, it reduces linking time for me on a sample project by ~5%. In the man page, it says that the flag means, `Do not put non-global symbols in the output file's symbol table`. However, when I stop at a breakpoint with LLDB, I'm still able to call static functions in the debugger just as easily with the flag as without. 5% would be nice, but can anyone shed some light on the implications of this flag?

**Comment by bjorn3** [comment]
I would guess that you compiled with debuginfo and that LLDB uses the debuginfo instead of the symbol table to lookup symbols when available.

**Comment by michaeleisel** [comment]
Gotcha, yeah I see a difference now without debugging symbols. Well then, unless anyone has any caveats they want to add, I'll update the list of recommended flags to speed things up
