### ISSUE TITLE
zld fails to link build script of backtrace-rs

### ISSUE THREAD

**Issue by TheOnlyMrCat** [michaeleisel/zld#94]
I'm using zld through cargo with rustflags: `"-C", "link-arg=-fuse-ld=/usr/local/bin/zld"`.

Compilation fails with the following warning and error:
```
ld: warning: ignoring file [project directory]/target/debug/deps/libcc-2e31f8b39e273fe3.rlib, building for macOS-x86_64 but attempting to link with file built for macOS-x86_64
          Undefined symbols for architecture x86_64:

          [A number of symbols from the `core`, `alloc`, `std`, and `cc` crates, referenced variously from `core`, `alloc`, `std`, and `build_script_build::build_android`]

ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Attached is the full log, if it is helps: [backtrace-rs_report.txt](https://github.com/michaeleisel/zld/files/7377829/backtrace-rs_report.txt)

Compilation succeeds using the default Apple linker

**Comment by TheOnlyMrCat** [comment]
Sure! Steps to reproduce:

As a dependency:
- Create a new cargo project (or use an existing one)
- Add `backtrace = "0.3.62"` to `Cargo.toml` (The most recent version at the time of writing)
- Run `cargo build`

Building the repository itself:
- Clone https://github.com/rust-lang/backtrace-rs
- Run `cargo build` in the cloned repository.

**Comment by michaeleisel** [comment]
Building with `cargo clean && RUSTFLAGS="-C link-arg=-fuse-ld=/path/to/zld" cargo build` succeeds for me for backtrace-rs

**Comment by michaeleisel** [comment]
Also, it looks like you're on an Intel mac, is that true?

**Comment by TheOnlyMrCat** [comment]
Curiously, the bug has disappeared for me as well. (Yes, intel mac, now on Monterey, same commit, with zld versions 1.3.1 and 1.3.3)

**Comment by michaeleisel** [comment]
hmm i'm curious of two things:
- is the linking deterministic? (does it produce the same executable each time?)
- can you try removing /tmp/zld-* and then running it twice? to test cached and non-cached cases

**Comment by TheOnlyMrCat** [comment]
The MD5 sum of `target/debug/build/backtrace-*/build-script-build` remains consistent, even when removing `/tmp/zld-*`.

I might have a time machine backup, so I could attempt to replicate the issue on a VM

**Comment by michaeleisel** [comment]
well, if the bug has disappeared, we can close. feel free to report if it happens again
