### ISSUE TITLE
Adding a conda-forge recipe

### ISSUE THREAD

**Issue by matter-it-does** [michaeleisel/zld#96]
Hi Michael. FYI I posted a PR https://github.com/conda-forge/staged-recipes/pull/17097 to add zld to conda-forge.

After several failed build attempts (as you can see in the commit history), I've resorted to using `homebrew-fixes-1.3.3` for the  source code. Let me know when that is merged into master. I'll be available in  https://gitter.im/conda-forge/conda-forge.github.io

Cheers.

**Comment by michaeleisel** [comment]
The homebrew fixes branch is a stopgap for homebrew's (IMO unnecessary) issues, and not necessarily going to be merged into master. Can you just use the prebuilt release instead?

**Comment by matter-it-does** [comment]
If I was maintaining my own recipe, yeah sure. But I don't think conda-forge folks accept that..

**Comment by michaeleisel** [comment]
How widely used is Conda? How much value can we expect out of supporting it? I'm unfamiliar with people using over homebrew

**Comment by matter-it-does** [comment]
Brew dropped support for 10.14 and I don't want to be building stuff all the time.
Conda supports even 10.9 for certain recipes.

**Comment by matter-it-does** [comment]
If you support that, you can even download the binary for your brew cask from anaconda.org like so https://anaconda.org/conda-forge/ccache/files
It's a superset in that sense.

**Comment by matter-it-does** [comment]
Oh I see that you have changed the code to build from source too. Still, brew is not a superset of conda as it doesn't allow binary download publicly.

**Comment by michaeleisel** [comment]
I'm not too interested in supporting below 10.14, and unfortunately I just haven't heard much of people using Conda for macOS. I'm going to close for now, but people are welcome to comment if they too need Conda support.

**Comment by z-aki** [comment]
You don't have to maintain the recipe.. just keep the abseil, mimalloc and tbb static library files.

**Comment by matter-it-does** [comment]
Just keeping static tbb, abseil, mimalloc helps a ton.
If you remove them, I'll try to replicate what you do after removing the stopgap homebrew solution.
